#!/bin/bash -x

set -x

bundle exec ruby create_database.rb
spanner-cli -p $SPANNER_TEST_PROJECT -i $SPANNER_TEST_INSTANCE -d $SPANNER_TEST_DATABASE -e 'CREATE TABLE `dynamic_items` (`id` INT64 NOT NULL, `col_timestamp` TIMESTAMP DEFAULT (CURRENT_TIMESTAMP())) PRIMARY KEY (`id`)'
spanner-cli -p $SPANNER_TEST_PROJECT -i $SPANNER_TEST_INSTANCE -d $SPANNER_TEST_DATABASE -e 'SHOW CREATE TABLE `dynamic_items`'
spanner-cli -p $SPANNER_TEST_PROJECT -i $SPANNER_TEST_INSTANCE -d $SPANNER_TEST_DATABASE -e 'SELECT COLUMN_NAME, COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME="dynamic_items"'

