on:
  push:
    branches:
      - main
  pull_request:
name: acceptance tests on emulator
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010
          - 9020:9020

    strategy:
      max-parallel: 4
      matrix:
        # ruby: ["2.6", "2.7", "3.0", "3.1"]
        ruby: ["3.1"]
        # ar: ["~> 6.0.6", "~> 6.1.7", "~> 7.0.4"]
        ar: ["~> 7.0.4"]
        # Exclude combinations that are not supported.
        exclude:
          - ruby: "3.0"
            ar: "~> 6.0.6"
          - ruby: "3.1"
            ar: "~> 6.0.6"
          - ruby: "2.6"
            ar: "~> 7.0.4"
    env:
      AR_VERSION: ${{ matrix.ar }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby
    # (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: false
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install

    - uses: actions/setup-go@v4
    - name: Install spanner-cli
      run: go install github.com/cloudspannerecosystem/spanner-cli@latest

    - name: Run acceptance tests on emulator
      run: bundle exec rake acceptance TEST=acceptance/cases/models/default_value_test.rb
      env:
        SPANNER_EMULATOR_HOST: localhost:9010
        SPANNER_TEST_PROJECT: test-project
        SPANNER_TEST_INSTANCE: test-instance

  emulator:
    runs-on: ubuntu-latest

    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010
          - 9020:9020
    env:
      SPANNER_EMULATOR_HOST: localhost:9010
      SPANNER_TEST_PROJECT: test-project
      SPANNER_TEST_INSTANCE: test-instance
      SPANNER_TEST_DATABASE: test-database
      AR_VERSION: "~> 7.0.4"
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
    - run: bundle install
    - uses: actions/setup-go@v4
    - name: Install spanner-cli
      run: go install github.com/cloudspannerecosystem/spanner-cli@latest
    - run: bundle exec ruby create_database.rb
    - run: $(go env GOPATH)/bin/spanner-cli -p $SPANNER_TEST_PROJECT -i $SPANNER_TEST_INSTANCE -d $SPANNER_TEST_DATABASE -e 'CREATE TABLE `dynamic_items` (`id` INT64 NOT NULL, `col_timestamp` TIMESTAMP DEFAULT (CURRENT_TIMESTAMP())) PRIMARY KEY (`id`)'
    - run: $(go env GOPATH)/bin/spanner-cli -p $SPANNER_TEST_PROJECT -i $SPANNER_TEST_INSTANCE -d $SPANNER_TEST_DATABASE -e 'SHOW CREATE TABLE `dynamic_items`'
    - run: $(go env GOPATH)/bin/spanner-cli -p $SPANNER_TEST_PROJECT -i $SPANNER_TEST_INSTANCE -d $SPANNER_TEST_DATABASE -e 'SELECT COLUMN_NAME, COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME="dynamic_items"'
